#!/usr/bin/env sh
#
# A rofi powered menu to execute power related action.
# Uses: amixer mpc poweroff reboot rofi rofi-prompt

ROFI_THEME="${ROFI_THEME:-/usr/share/rofi/themes/Arc-Dark.rasi}"

power_off=' power off'
reboot=' reboot'
lock=' lock screen'
suspend='鈴 suspend to RAM'
log_out=' logout'

# old: appsmenu.rasi
chosen=$(printf '%s;%s;%s;%s;%s\n' "$power_off" "$reboot" "$lock" "$suspend" \
                                   "$log_out" \
    | rofi -theme $ROFI_THEME \
           -dmenu \
           -sep ';' \
           -selected-row 2)

function lock() {
    swaylock -f -c 000000
}

case "$chosen" in
    "$power_off")
        ~/.config/sway/rofi-prompt --query 'Shutdown?' && systemctl poweroff
        ;;

    "$reboot")
        ~/.config/sway/rofi-prompt --query 'Reboot?' && systemctl reboot
        ;;

    "$lock")
        lock
        ;;

    "$suspend")
        lock && systemctl suspend
        ;;

    "$log_out")
        ~/.config/sway/rofi-prompt --query 'Logout?' && swaymsg exit
        ;;

    *) exit 1 ;;
esac

