#!/bin/sh

GOVERNOR=$1
CPUFREQ_SET=/usr/bin/cpufreq-set
CPUFREQ_INFO=/usr/bin/cpufreq-info
CPUFREQ_OPTIONS=
SUDO=

if [ `whoami` != "root" ]; then
    SUDO="sudo"
fi

check_governor_avail() {
	info="/sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors"
	if [ -f $info ] && grep -q "\<$GOVERNOR\>" $info ; then
		return 0;
	fi
	return 1;
}

[ -x $CPUFREQ_SET ] || exit 0

if [ -n "$GOVERNOR" ] ; then
	CPUFREQ_OPTIONS="$CPUFREQ_OPTIONS --governor $GOVERNOR"
fi

CPUS=$(cat /proc/stat|sed -ne 's/^cpu\([[:digit:]]\+\).*/\1/p')
RETVAL=0
echo "Setting '$GOVERNOR' CPUFreq governor"
if check_governor_avail ; then
    for cpu in $CPUS ; do
        echo "CPU${cpu}"
        $SUDO $CPUFREQ_SET --cpu $cpu $CPUFREQ_OPTIONS 2>&1 > /dev/null || \
            RETVAL=$?
    done
else
    echo "ERROR Governor '$GOVERNOR' not available"
    exit 1
fi

