#!/bin/bash

#get connection of monitor with number $MON_NO
MON_CON=$(xrandr | grep connected | grep primary | tr -s " " | cut -d " " -f 4)

#for each id of wacom devices set correct output monitor
xsetwacom list devices |
while IFS= read -r line; do
  #get id of wacom device in line
  WACOM_ID="$(echo $line | sed 's/.*id: //' | cut -d " " -f 1)"
  #set monitor as output
  xsetwacom --set $WACOM_ID MapToOutput $MON_CON
done

echo "Changed monitor for all wacom devices."
