#!/bin/bash

# definition of MAC addresses
desktop_nils="70:85:C2:F9:2D:6E"

zerotier_gateway_address="10.3.237.144"

echo "Which PC to wake?"
echo "d) desktop-nils"
echo "q) quit"
read input1

echo "Via?"
echo "d) Direct"
echo "z) ZeroTier One"
echo "q) quit"
read input2

case $input2 in
  d)
    WOL_COMMAND="wakeonlan"
    ;;
  z)
    WOL_COMMAND="ssh nils@$zerotier_gateway_address wakeonlan"
    ;;
  Q|q)
    exit 0
    ;;
esac

case $input1 in
  d)
    $WOL_COMMAND $desktop_nils
    ;;
  Q|q)
    break
    ;;
esac
