#!/bin/bash
# Shortcut for a Michurin CLI client.
#
# Author: machaerus
# https://gitlab.com/machaerus

"$HOME/.conda/envs/michurin/bin/python" "$HOME/Sync/Projekty/project_michurin/client/michurin.py" "$@"
