#!/bin/bash

# exit on failure
set -e

package=$1
file=$2

if [[ -z "$package" ]] || [[ -z "$file" ]]; then
    echo "Usage: apt-diff <package> <file>"
    exit 1
fi

PWD="`pwd`"

mkdir -p /tmp/$package
cd /tmp/$package

# you could also get the file from a package mirror if you have
#  an older version of apt-get that doesn't support 'download' 
#  or if you would like more control over what package version
#  you are downloading.
# (e.g. http://archive.ubuntu.com/ubuntu/pool/main/)
apt-get download $package

# deb package files are ar archives
ar vx ${package}*.deb

if [ -e "data.tar.gz" ]; then
    # containing some compressed tar archives
    tar xzf data.tar.gz
elif [ -e "data.tar.xz" ]; then
    tar -x --xz -f data.tar.xz
fi

# now you have the files

# you can get diffs for all of the files in etc if you would like
echo "Your diff of ./$file and /$file:"
diff ./$file /$file

cd $PWD
