#!/bin/zsh

ROMIDS=()
SECTIONS=()

usage() {
    echo "Usage:   n-roms-dl <ROM name> <section id>"
    echo "Example: n-roms-dl \"Zelda 4 (D)\" snes"
    exit 1
}

if [ -e "$1" ]; then
    # First param was a file. Read the rom names from the file
    while read line; do
        data=("${(s/:/)line}")
        ROMIDS+=( $data[1] )
        SECTIONS+=( $data[2] )
    done < "$1"
else
    ROMIDS=("$1")
    SECTIONS=("$2")
fi

date > log.txt
C=1
for ROMID in $ROMIDS; do
    SECTION=$SECTIONS[$C]
    echo "Downloading $ROMID in section $SECTION"
    let C++

    if [[ -z "$ROMID" ]] || [[ -z "$SECTION" ]]; then
        usage
    fi

    rm -f cookies.txt
    rm -f rom.zip
    curl -c cookies.txt "http://www.n-roms.de/$SECTION/index.php?action=details&id=$ROMID" > /dev/null
    DL_URL=$(curl -b cookies.txt "http://www.n-roms.de/$SECTION/index.php?action=load&id=$ROMID" | grep -o -E -e "URL=[^\"]*" | sed 's/URL=//g' | python -c "import urllib; import sys; print urllib.quote(sys.stdin.read().strip()).replace('%3A//', '://')")

    echo "$DL_URL" | grep "index.php" >/dev/null 2>&1
    if [ "$?" -eq "0" ]; then
        echo "ERROR: This was a redirect to the frontpage..."
        continue
    fi

    echo "Dowloading $DL_URL..."

    mkdir -p "$SECTION"

    curl "$DL_URL" -o rom.zip >> log.txt && unzip -d $SECTION -n rom.zip >> log.txt && rm rom.zip
done
